[package]
name = "exploit-rust"
description = "launches a buffer overflow exploit on a tcpserver\n friendly - sends a regular message \n fuzzer - overflows the buffer with pattern \n eip - overwrites the instruction pointer with deadbeef value \n exploit - overflows the buffer and executes a shellcode" 
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
