[package]
name = "exploit-rust"
description = "launches a buffer overflow exploit on a tcpserver"

version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
